#!/bin/bash

[ ! -d $HOME/bin ] && mkdir -p $HOME/bin -v

mkdir LIBRARIES RAW -v

ln -s $HOME/VirWGS/SCRIPTS/* $HOME/bin

bash $HOME/bin/GUPPY

bash $HOME/bin/CONDA

mamba env create -f ENVS/depth.yml

mamba env create -f ENVS/illumina.yml

mamba env create -f ENVS/minion-qc.yml

mamba env create -f ENVS/minion.yml
