#!/bin/bash

MYSHELL=$(echo $SHELL | awk -F/ '{print $NF}')

echo 'export PATH=$HOME/vgap/SCRIPTS:/usr/local/share/rsi/idl/bin:$PATH' >> $HOME/.${MYSHELL}rc

GUPPY_VERSION=5.0.14

if [[ -z "$(which guppy_basecaller)" ]]; then
    cd
    curl https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy_"$GUPPY_VERSION"_linux64.tar.gz -o ont-guppy.tar.gz
    tar -vzxf ont-guppy.tar.gz
    rm -rf ont-guppy.tar.gz
    echo 'export PATH=$HOME/ont-guppy/bin:/usr/local/share/rsi/idl/bin:$PATH' >> $HOME/.${MYSHELL}rc
    export PATH=$HOME/ont-guppy/bin:/usr/local/share/rsi/idl/bin:$PATH
else
    if [[ "$(guppy_basecaller --version | awk -F" " '{print $NF}' | awk -F+ '{print $1}' | sed -n '1p')" < "$GUPPY_VERSION" ]]; then
        cd
        rm -rf ont-guppy
        curl https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy_"$GUPPY_VERSION"_linux64.tar.gz -o ont-guppy.tar.gz
        tar -vzxf ont-guppy.tar.gz
        rm -rf ont-guppy.tar.gz
    else
        guppy_basecaller --version
    fi
fi

if [[ -z "$(which conda)" ]]; then
    cd
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    bash Miniconda3-latest-Linux-x86_64.sh -bfp miniconda3
    rm Miniconda3-latest-Linux-x86_64.sh
    echo 'export PATH=$HOME/miniconda3/bin:/usr/local/share/rsi/idl/bin:$PATH' >> $HOME/.${MYSHELL}rc
    export PATH=$HOME/miniconda3/bin:/usr/local/share/rsi/idl/bin:$PATH
    conda install -y -c conda-forge mamba
    mamba update -y -c conda-forge -c anaconda -c bioconda -c defaults -n base conda
    mamba create -y -n illumina_assembly -c conda-forge -c anaconda -c bioconda -c defaults bwa exonerate fastqc ivar mafft minimap2 multiqc pilon samtools seqkit seqtk trimmomatic
    mamba create -y -n ont_assembly -c conda-forge -c anaconda -c bioconda -c defaults artic exonerate seqtk
    mamba create -y -n ont_qc -c conda-forge -c anaconda -c bioconda -c defaults python=3.6 pycoqc
    mamba create -y -n plot -c conda-forge -c anaconda -c bioconda -c defaults ghostscript numpy pandas pysam seaborn
else
    if [[ -z "$(which mamba)" ]]; then
        conda install -y -c conda-forge mamba
        mamba update -y -c conda-forge -c anaconda -c bioconda -c defaults -n base conda
        if [[ -z "$(conda env list | grep "illumina_assembly|ont_assembly|ont_qc|plot")" ]]; then
            mamba create -y -n illumina_assembly -c conda-forge -c anaconda -c bioconda -c defaults bwa exonerate fastqc ivar mafft minimap2 multiqc pilon samtools seqkit seqtk trimmomatic
            mamba create -y -n ont_assembly -c conda-forge -c anaconda -c bioconda -c defaults artic exonerate seqtk
            mamba create -y -n ont_qc -c conda-forge -c anaconda -c bioconda -c defaults python=3.6 pycoqc
            mamba create -y -n plot -c conda-forge -c anaconda -c bioconda -c defaults ghostscript numpy pandas pysam seaborn
        else
            mamba update -y -n illumina_assembly -c conda-forge -c anaconda -c bioconda -c defaults --all
            mamba update -y -n ont_assembly -c conda-forge -c anaconda -c bioconda -c defaults --all
            mamba update -y -n ont_qc -c conda-forge -c anaconda -c bioconda -c defaults --all
            mamba update -y -n plot -c conda-forge -c anaconda -c bioconda -c defaults --all
        fi
    else
        mamba update -y -c conda-forge -c anaconda -c bioconda -c defaults -n base conda
        if [[ -z "$(conda env list | grep "illumina_assembly|ont_assembly|ont_qc|plot")" ]]; then
            mamba create -y -n illumina_assembly -c conda-forge -c anaconda -c bioconda -c defaults bwa exonerate fastqc ivar mafft minimap2 multiqc pilon samtools seqkit seqtk trimmomatic
            mamba create -y -n ont_assembly -c conda-forge -c anaconda -c bioconda -c defaults artic exonerate seqtk
            mamba create -y -n ont_qc -c conda-forge -c anaconda -c bioconda -c defaults python=3.6 pycoqc
            mamba create -y -n plot -c conda-forge -c anaconda -c bioconda -c defaults ghostscript numpy pandas pysam seaborn
        else
            mamba update -y -n illumina_assembly -c conda-forge -c anaconda -c bioconda -c defaults --all
            mamba update -y -n ont_assembly -c conda-forge -c anaconda -c bioconda -c defaults --all
            mamba update -y -n ont_qc -c conda-forge -c anaconda -c bioconda -c defaults --all
            mamba update -y -n plot -c conda-forge -c anaconda -c bioconda -c defaults --all
       fi
    fi
fi

if [[ -z "$(which fastcov.py)" ]]; then
    cd
    git clone https://github.com/RaverJay/fastcov
    cd fastcov
    echo 'export PATH=$HOME/fastcov:/usr/local/share/rsi/idl/bin:$PATH' >> $HOME/.${MYSHELL}rc
    export PATH=$HOME/fastcov:/usr/local/share/rsi/idl/bin:$PATH
else
    source activate plot
    fastcov.py --help
fi
