#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Universidade Federal da Bahia, Brazil
# URL: https://github.com/lpmor22
# date: 24 APR 2021

[ -d "$HOME/miniconda3" ] && rm -rf $HOME/miniconda3 $HOME/.conda*

cd

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

bash Miniconda3-latest-Linux-x86_64.sh -bfp miniconda3

rm Miniconda3-latest-Linux-x86_64.sh

echo 'export PATH=$HOME/miniconda3/bin:/usr/local/share/rsi/idl/bin:$PATH' >> $HOME/.bashrc

echo 'export PATH=$HOME/miniconda3/bin:/usr/local/share/rsi/idl/bin:$PATH' >> $HOME/.zshrc

export PATH=$HOME/miniconda3/bin:/usr/local/share/rsi/idl/bin:$PATH

conda install -y -c conda-forge mamba

mamba update -y -n base conda
