#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Oswaldo Cruz Foundation, Gonçalo Moniz Institute, Bahia, Brazil
# URL: https://lpmor22.github.io
# date: 29 APR 2021

while getopts ":r:s:dt:" opt; do
	case $opt in
		r ) RAWPATH="$OPTARG";;
		s ) PRIMERSCHEME="$OPTARG";;
		d ) PLOTDEPTH=yes;;
		t ) THREADS="$OPTARG";;
	esac
done
shift $((OPTIND -1))

if [[ -z "$RAWPATH" ]] || [[ -z "$PRIMERSCHEME" ]] || [[ -z "$THREADS" ]]; then
	echo "Assembly pipeline for WGS using Illumina

Usage: $(basename $0) [-r RAWPATH] [-s PRIMERSCHEME] [-t THREADS]

-r  The FULL PATH to the directory containing the raw sequencing data downloaded from Illumina's BaseSpace Sequence Hub (fastq.gz files).
-s  The prime scheme information (example: nCoV-2019/FIOCRUZ_2kb_v1 or nCoV-2019/ARTIC_V3).
-t  Num tasks to process concurrently."
	exit 1
fi

assembly_illumina.sh $PRIMERSCHEME $RAWPATH $THREADS >> $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)_log.txt

#use -d only for SARS-CoV-2 -- https://github.com/ItokawaK/Alt_nCov2019_primers
if [[ -n "$PLOTDEPTH" ]]; then
	source activate depth
	plot_depth_ncov19.py -t $THREADS --bams $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.primertrimmed.rg.sorted.bam -o $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/CONSENSUS/$(basename $RAWPATH).depth.pdf -r $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.reference.fasta # https://github.com/ItokawaK/Alt_nCov2019_primers
fi

rm -rf $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.reference.fasta*

rm -rf $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.score.bed

tar -czf $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH).tar.gz -P $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)*

[ -f ./nohup.out ] && rm -rf ./nohup.out
