#!/bin/bash

while getopts ":r:s:dt:" opt; do
	case $opt in
		r ) RAWPATH="$OPTARG";;
		s ) PRIMERSCHEME="$OPTARG";;
		d ) PLOTDEPTH=yes;;
		t ) THREADS="$OPTARG";;
	esac
done
shift $((OPTIND -1))

if [[ -z "$RAWPATH" ]] || [[ -z "$PRIMERSCHEME" ]] || [[ -z "$THREADS" ]]; then
	echo "Assembly pipeline for WGS using Illumina

Usage: $(basename $0) [-r RAWPATH] [-s PRIMERSCHEME] [-d] [-t THREADS]

Options:
-r  The PATH to the directory containing the raw sequencing data downloaded from Illumina's BaseSpace Sequence Hub (fastq.gz files).
-s  The prime scheme information (example: nCoV-2019/FIOCRUZ_2kb_v1 or nCoV-2019/ARTIC_V3).
-d  Generates depth plots in sigle PDF file from multiple BAM files to briefly check coverages [from ItokawaK/Alt_nCov2019_primers].
-t  Num tasks to process concurrently."
	exit 1
fi

assembly_illumina.sh $PRIMERSCHEME $RAWPATH $THREADS >> $HOME/WGS/LIBRARIES/$(basename $RAWPATH)_log.txt

if [[ -n "$PLOTDEPTH" ]]; then
	source activate depth
	plot_depth.py -t $THREADS --bams $HOME/WGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.trimmed.sorted.bam -o $HOME/WGS/LIBRARIES/$(basename $RAWPATH)/CONSENSUS/$(basename $RAWPATH).depth.pdf -r $HOME/WGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.reference.fasta # https://github.com/ItokawaK/Alt_nCov2019_primers
fi

rm -rf $HOME/WGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.reference.fasta*

rm -rf $HOME/WGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.score.bed

tar -czf $HOME/WGS/LIBRARIES/$(basename $RAWPATH).tar.gz -P $HOME/WGS/LIBRARIES/$(basename $RAWPATH)*

[ -f ./nohup.out ] && rm -rf ./nohup.out
