#!/bin/bash

# author: Laise de Moraes <laisepaixao@live.com>
# institution: Oswaldo Cruz Foundation, Gonçalo Moniz Institute, Bahia, Brazil
# URL: https://lpmor22.github.io
# date: 28 APR 2021

while getopts ":r:s:dt:g:c:" opt; do
	case $opt in
		r ) RAWPATH="$OPTARG";;
		s ) SAMPLESHEET="$OPTARG";;
		d ) PLOTDEPTH=yes;;
		t ) THREADS="$OPTARG";;
		g ) CUDACORES="$OPTARG";; # NVIDIAGeForceRTX2060=32; NVIDIAGeForceRTX2080=64
		c ) NUMCALLERS="$OPTARG";; # NVIDIAGeForceRTX2060=60; NVIDIAGeForceRTX2080=46
	esac
done
shift $((OPTIND -1))

if [[ -z "$RAWPATH" ]] || [[ -z "$SAMPLESHEET" ]] || [[ -z "$THREADS" ]] || [[ -z "$CUDACORES" ]] || [[ -z "$NUMCALLERS" ]]; then
	echo "Assembly pipeline for WGS using MinION

Usage: $(basename $0) [-r RAWPATH] [-s SAMPLESHEET] [-t THREADS] [-g CUDACORES] [-c NUMCALLERS]

-r  The FULL PATH to the directory containing the raw sequencing data (fast5 files).
-s  The FULL PATH to the sample sheet (.csv) file.
-t  Number of tasks to process concurrently.
-g  Number of GPU cuda cores [for guppy_basecaller].
-c  Number of parallel basecallers to FAST5 file [for guppy_basecaller]."
	exit 1
fi

assembly_minion.sh $SAMPLESHEET $RAWPATH $THREADS $CUDACORES $NUMCALLERS >> $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)_log.txt

#use -d only for SARS-CoV-2 -- https://github.com/ItokawaK/Alt_nCov2019_primers
if [[ -n "$PLOTDEPTH" ]]; then
	source activate depth
	plot_depth_ncov19.py --bams $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.primertrimmed.rg.sorted.bam -o $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/CONSENSUS/$(basename $RAWPATH).depth.pdf -r $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.reference.fasta # https://github.com/ItokawaK/Alt_nCov2019_primers
fi

rm -rf $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.reference.fasta*

rm -rf $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.score.bed

tar -czf $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH).tar.gz -P $HOME/VirWGS/LIBRARIES/$(basename $RAWPATH)*

[ -f ./nohup.out ] && rm -rf ./nohup.out
