#!/bin/bash

while getopts ":r:s:dt:g:c:" opt; do
	case $opt in
		r ) RAWPATH="$OPTARG";;
		s ) SAMPLESHEET="$OPTARG";;
		d ) PLOTDEPTH=yes;;
		t ) THREADS="$OPTARG";;
		g ) CUDACORES="$OPTARG";; # NVIDIAGeForceRTX2060=32; NVIDIAGeForceRTX2080=64
		c ) NUMCALLERS="$OPTARG";; # NVIDIAGeForceRTX2060=60; NVIDIAGeForceRTX2080=46
	esac
done
shift $((OPTIND -1))

if [[ -z "$RAWPATH" ]] || [[ -z "$SAMPLESHEET" ]] || [[ -z "$THREADS" ]] || [[ -z "$CUDACORES" ]] || [[ -z "$NUMCALLERS" ]]; then
	echo "Assembly pipeline for WGS using ONT

Usage: $(basename $0) [-r RAWPATH] [-s SAMPLESHEET] [-t THREADS] [-g CUDACORES] [-c NUMCALLERS]

-r  The FULL PATH to the directory containing the raw sequencing data (fast5 files).
-s  The FULL PATH to the sample sheet (.csv) file.
-d  Generates depth plots in PDF file from BAM files to briefly check coverages.
-t  Number of tasks to process concurrently.
-g  Number of GPU cuda cores [for guppy_basecaller].
-c  Number of parallel basecallers to FAST5 file [for guppy_basecaller]."
	exit 1
fi

bg() {

    start=$(date +%s.%N)

    VGAP=$(find $HOME -type d -name "vgapWGS-ONT")

    source activate vgapWGS-ONT

    assembly_minion.sh $SAMPLESHEET $RAWPATH $THREADS $CUDACORES $NUMCALLERS

    source activate plot

    if [[ -n "$PLOTDEPTH" ]]; then
        for i in $(find $VGAP/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/ -type f -name "*.primertrimmed.rg.sorted.bam" | while read o; do basename $o | awk -F. '{print $1}'; done | sort -u); do fastcov -l $VGAP/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/"$i".primertrimmed.rg.sorted.bam -o $VGAP/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/"$i".coverage.pdf; done
        gs -dSAFER -r3000 -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -sOUTPUTFILE=$VGAP/LIBRARIES/$(basename $RAWPATH)/CONSENSUS/$(basename $RAWPATH).depth.pdf $VGAP/LIBRARIES/$(basename $RAWPATH)/ANALYSIS/*.pdf
    fi

    end=$(date +%s.%N)

    runtime=$(python -c "print(${end} - ${start})")

    echo "" && echo "Done. The runtime was $runtime seconds."

}

bg $1 $2 $3 $4 $5 &>"$VGAP/LIBRARIES/$(basename $RAWPATH)"_log.txt &
